apiVersion: apps/v1
kind: Deployment
metadata:
  name: projeto_github_actions
spec:
  replicas: 1
  selector:
    matchLabels:
      app: projeto_github_actions
  template:
    metadata:
      labels:
        app: projeto_github_actions
    spec:
      containers:
      - name: projeto_github_actions
        image: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: projeto_github_actions-service
spec:
  type: LoadBalancer
  selector:
    app: projeto_github_actions
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
